version: '3'

services:
    my-postres:
        image: 'postgres:latest'
        environment:
        - POSTGRES_PASSWORD=${PGPASSWORD}
        
    my-redis:
        image: 'redis:latest'
    
    my-backend:
        build: 
            dockerfile: Dockerfile.dev
            context: ./backend
        volumes:
            - /opt/app/node_modules
            - ./backend:/opt/app
        ports: 
            - '5000:5000'
        environment: 
            - REDIS_HOST=${REDIS_HOST}
            - REDIS_PORT=${REDIS_PORT}
            - PGUSER=${PGUSER}
            - PGHOST=${PGHOST}
            - PGDATABASE=${PGDATABASE}
            - PGPASSWORD=${PGPASSWORD}
            - PGPORT=${PGPORT}
            
    my-frontend:
        build:
            dockerfile: Dockerfile.dev
            context: ./frontend
        volumes:
            - /opt/app/node_modules
            - ./frontend:/opt/app
        tty: true
        
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '8080:80'
        