sudo: required

services:
    - docker
    
before_install:
    - docker build -t xvoxin/docker-front -f multicon-app/frontend/Dockerfile.dev multicon-app/frontend/.
    
script:
    - docker run -e CI=true xvoxin/docker-front yarn test